#!/usr/bin/env bash
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


[package]
name = "vaticle-dependencies"
version = "0.0.0"

[lib]
path = "" # ignored by cargo generate-lockfile

[dependencies]
alcoholic_jwt = "=4091.0.0"
async-stripe = { version = "=0.22.2", features = ["runtime-tokio-hyper"] }
async-trait = "=0.1.59"
axum = { version = "=0.5.15", features = ["ws"] }
bincode = "=1.3.3"
chrono = "=0.4.38"
clap = "=4.0.26"
coerce = "=0.8.3"
crossbeam = "=0.8.2"
cxx = "=1.0.59"
enum_dispatch = "=0.3.11"
env_logger = "=0.10.0"
fluvio-helm = "=0.4.3"
futures = { version = "=0.3.21", features = ["executor", "thread-pool"] }
hmac = "=0.12.1"
http = "=0.2.8"
itertools = "=0.10.3"
jsonwebtoken = "=8.3.0"
k8s-openapi = { version = "=0.16.0", features = ["v1_25"] }
kube = { version = "=0.77.0", features = ["runtime", "derive"] }
log = "=0.4.17"
lz4 = "=1.24.0"
macro_rules_attribute = "=0.2.0"
maybe-async = "=0.2.7"
mime = "=0.3.16"
mime_guess = "=2.0.4"
pest = "=2.7.4"
pest_derive = "=2.7.4"
pprof = { version = "0.13.0", features = ["flamegraph", "criterion"] }
prost = "=0.11.0"
prost-build = "=0.11.0"
rand = "=0.8.5"
regex = "=1.6.0"
reqwest = { version = "=0.11.12", features = ["json"] }
rocksdb = { version = "=0.22.0", features = ["lz4"], default_features = false }
same-file = "=1.0.6"
seahash = "=4.1.0"
serde = "=1.0.152"
serde_json = "=1.0"
serde_yaml = "=0.9.25"
sha2 = "=0.10.6"
tempdir = "=0.3.7"
tokio = { version = "=1.28.2", features = ["rt", "rt-multi-thread"] }
tokio-retry = "=0.3.0"
tokio-stream = "=0.1.11"
tonic = { version = "=0.8.0", features = ["tls", "tls-roots"] }
tonic-build = "=0.8.0"
tower = "=0.4.13"
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.16", features = ["env-filter"] }
uuid = { version = "=1.1.2", features = ["fast-rng", "v4"] }
webpki = "=0.22.2"

[dev-dependencies]
async-std = { version = "=1.12.0", features = ["attributes"] }
cbindgen = "=0.24.5"
criterion = "=0.5.1"
cucumber = "=0.19.1"
rand_core = "0.3.1"
serial_test = "=0.9.0"
smol = "=1.3.0"
xoshiro = "0.0.5"
