#!/usr/bin/env bash
#
# Copyright (C) 2022 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

[package]
name = "vaticle-dependencies"
version = "0.0.0"

[lib]
path = "" # ignored by cargo generate-lockfile

[dependencies]
hmac = "=0.12.1"
alcoholic_jwt = "=4091.0.0"
async-stripe = { version = "=0.22.2", features = ["runtime-tokio-hyper"] }
async-trait = "=0.1.59"
axum = { version = "=0.5.15", features = ["ws"] }
chrono = "=0.4.23"
clap = "=4.0.26"
crossbeam = "=0.8.2"
coerce = "0.8.3"
cxx = "=1.0.59"
enum_dispatch = "=0.3.11"
fluvio-helm = "=0.4.3"
futures = { version = "=0.3.21", features = ["executor", "thread-pool"] }
http = "=0.2.8"
itertools = "=0.10.3"
k8s-openapi = { version = "=0.16.0", features = ["v1_25"] }
kube = { version = "=0.77.0", features = ["runtime", "derive"] }
log = "=0.4.17"
mime = "=0.3.16"
mime_guess = "=2.0.4"
pest = "=2.4.0"
pest_derive = "=2.4.0"
prost = "=0.11.0"
prost-build = "=0.11.0"
regex = "=1.6.0"
reqwest = { version = "=0.11.12", features = ["json"] }
rocksdb = {version="=0.19.0", features = ["lz4"], default-features = false }
serde = "=1.0.152"
serde_json = "=1.0"
sha2 = "=0.10.6"
tokio = { version = "=1.24.1", features = ["rt", "rt-multi-thread"] }
tokio-stream = "=0.1.11"
tonic = { version = "=0.8.0", features = ["tls"] }
tonic-build = "=0.8.0"
tower = "=0.4.13"
tracing = "=0.1.37"
tracing-subscriber = "=0.3.16"
uuid = { version = "=1.1.2", features = ["fast-rng", "v4"] }

[dev-dependencies]
async-std = { version = "=1.12.0", features = ["attributes"] }
cucumber = "=0.19.1"
serial_test = "=0.9.0"
smol = "=1.3.0"
