[package]
name = "vaticle-dependencies"
version = "0.0.0"

[lib]
path = "" # ignored by cargo raze

[dependencies]
antlr-rust = "0.2.0"
cxx = "1.0.59"
futures = { version = "0.3.21", features = ["executor", "thread-pool"] }
rocksdb = "0.17.0"
tokio = { version = "0.2.25", features = ["macros", "sync"] } # tokio 0.2.25 is used by grpc
uuid = { version = "0.8.2", features = ["v4"] }

# gRPC dependencies - TODO: clean up
protobuf = { version = "2.18.2", features = ["with-bytes"] }
protobuf-codegen = "2.18.2"
grpc = "0.8.3"
protoc-rust-grpc = "0.8.3"
grpc-protobuf = "0.8.3"

grpc-compiler = "0.8.3"
tls-api = "0.1.22"
tls-api-stub = "0.1.22"
log = "0.4.6"

[dev-dependencies]
derivative = "2.2.0"
enum_dispatch = "0.3.8"

[package.metadata.raze]
# The path at which to write output files.
#
# `cargo raze` will generate Bazel-compatible BUILD files into this path.
# This can either be a relative path (e.g. "foo/bar"), relative to this
# Cargo.toml file; or relative to the Bazel workspace root (e.g. "//foo/bar").
workspace_path = "//library/crates"

# This causes aliases for dependencies to be rendered in the BUILD
# file located next to this `Cargo.toml` file.
package_aliases_dir = "."

# The set of targets to generate BUILD rules for.
targets = [
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
]

# The two acceptable options are "Remote" and "Vendored" which
# is used to indicate whether the user is using a non-vendored or
# vendored set of dependencies.
genmode = "Remote"

# gRPC arguments and aliased targets
[package.metadata.raze.crates.lazy_static.'1.4.0']
additional_flags = [
    "--cfg=lazy_static_heap_impl",
]

#[package.metadata.raze.crates.protobuf.'2.23.0']
#patches = ["@rules_rust//proto/raze/patch:protobuf-2.8.2.patch"]
#patch_args = ["-p1"]

[package.metadata.raze.crates.protobuf-codegen.'2.18.2']
extra_aliased_targets = ["cargo_bin_protoc_gen_rust"]

[package.metadata.raze.crates.grpc-compiler.'0.8.3']
extra_aliased_targets = ["cargo_bin_protoc_gen_rust_grpc"]
